sonar.projectKey=DAISORNA_casino-royale
sonar.organization=daisorna-1
sonar.projectName=casino-royale

sonar.sources=apps/frontend/src,apps/backend/CasinoDesk.Api,js,css,pages,index.html
sonar.tests=apps/frontend/src
sonar.test.inclusions=apps/frontend/src/**/*.test.ts,apps/frontend/src/**/*.test.tsx

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/bin/**,**/obj/**
sonar.javascript.lcov.reportPaths=apps/frontend/coverage/lcov.info
sonar.sourceEncoding=UTF-8
